---
- name: Prepare systems for Ansible management
  hosts: servers
  gather_facts: false

  roles:
    - robertdebock.bootstrap

- name: Configure OS and apply baseline hardening
  hosts: servers
  gather_facts: true

  roles:
    - os_setup
    - geerlingguy.security
