---
- name: Update apt cache and run dist upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install packages via apt
  apt:
    name:
      - qemu-guest-agent
      - xterm
      - nfs-kernel-server

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
  when: reboot_required_file.stat.exists == true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
