---
- name: Create kube directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: 0700

- name: Set primary K3s cluster facts
  ansible.builtin.set_fact:
    k3s_primary_host: "{{ groups['k3s_cluster'][0] }}"
    vip_address: "{{ hostvars[groups['k3s_cluster'][0]].k3s_registration_address
      | default(ansible_host) }}"

- name: Fetch the kubeconfig file directly from the primary K3s node
  delegate_to: "{{ k3s_primary_host }}"
  become: true
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/kubeconfig
    flat: true
    validate_checksum: false
  run_once: true

- name: Copy the kubeconfig file to ansible host
  ansible.builtin.copy:
    src: /tmp/kubeconfig
    dest: "{{ ansible_user_dir }}/.kube/config"
    mode: 0600

- name: Configure kubectl cluster for K3s VIP address
  ansible.builtin.command: >-
    kubectl config set-cluster default
      --server https://{{ vip_address }}:6443
  environment:
    KUBECONFIG: "{{ ansible_user_dir }}/.kube/config"
  changed_when: true

- name: Clean tmp kubeconfig
  ansible.builtin.file:
    path: /tmp/kubeconfig
    state: absent
