host_identity_timezone: ENC[AES256_GCM,data:q0sdLqTe5CxmhCb2Bow=,iv:dKyU9uIuuGsxVB+i+YoU34ON2Sxi26mza5VNJ3Sw+pw=,tag:jNZMe4elDVJYe7w1QSjOxw==,type:str]
security_baseline_authorized_keys:
    - ENC[AES256_GCM,data:S+NlQxcoL6SlgAAIzQPLkPKInHC5rhNi0ikjUSKxiXobGxdB2ATaBJmxa7wPkZkXT4Pf1peeonQ2xI7rSz1dpe5bB2OxW6+pLl/jm+vLA/51JOTyN2WQ6PRhdPRH0WL6Xnrc5dJ+Zkyb0VYx3oYRyOiG,iv:Fb03RPF28T2buXQOgt3jijFK65zoF1uiU1XPGMAjWL8=,tag:iAD2mfyuJ2EeEyu4RMVRQw==,type:str]
security_baseline_management_sources:
    - ENC[AES256_GCM,data:V824iPg1mPuUU0HP10Cn,iv:4fwO12q0pSl1nsDRtA9u1a/PURsCZjaSC4os8D7Px6c=,tag:UhIzqSw+IBDntIRMzwDarQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZkZUL3hTUkhKc1g3Yzg0
            QVBhcUFPUUVQRnhIU0pnQjZpM0g3Ukhac1VzCjRuRHpSbnl5UFA0NzZhNDcxUGV0
            RVNqN1Y2QXpRTklRSGQ5Nk5qV1ZZc1kKLS0tIG13NHd2allPOUlqWVE4OGY2T1FX
            ZUxZM04wME1NaHFyQkJMU1ROamtrUVkKSOO2tpTWittOoUk5cIhKRbVcwwZJDt5i
            r+yjQSzTlKYmvSHKscGdskUghrRuavNiTB5kWZrGnFxP2xMrYJPaVw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehm0ehd2v2emfuycf2p0suhg94ej29zcu96ffmh3t6afchhjd99sxc4984
    encrypted_regex: ^(.*)$
    lastmodified: "2026-09-07T14:39:26Z"
    mac: ENC[AES256_GCM,data:tcrvvkgnqOMcLW6FHeh+1B8skHcXJsYTlwF8VoAHhySteyrIYyuUmXdF9ywCHd/kc9OaeOkYmpz6qe7Xa5mw0ernMUnQe4yTUrp8v2NmQHgOiNb7+Eph5ae4lwBX1vEwGD6yDQ29kKwthZ5zppy6AJymXtMvpP00uwb9HiXUtKE=,iv:3WnnELsw7d83kz0DwFgob9hjde4vVP2ancolwwNwFIU=,tag:I2cfrLB0ce0942XUxr0SMA==,type:str]
    version: 3.13.2
