---
- hosts: k3s_cluster
  become: true
  roles:
    - geerlingguy.docker

- hosts: k3s_cluster
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - prereq
    - download

- hosts: master
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - k3s/master

- hosts: node
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - k3s/node

- hosts: master
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - k3s/post
~
