---
- hosts: all
  connection: local
  gather_facts: false
  roles:
    - ssh/scankeys

- hosts: k3s_cluster
  become: true
  roles:
    - geerlingguy.docker

- hosts: k3s_cluster
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - prereq
    - download

- hosts: master
  collections:
    - ksiggins.k3s
  roles:
    - role: k3s/master
      # gather facts for the root vs logged-in user by specifying become
      # at the role level instead of play to ensure proper kube config
      become: true

- hosts: node
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - k3s/node

- hosts: master
  become: true
  collections:
    - ksiggins.k3s
  roles:
    - k3s/post
    - k3s/nginx

- hosts: all
  roles:
    - k3s/kubeconfig
