---
collections:
  - name: ksiggins.k3s
    source: https://github.com/ksiggins/k3s-ansible.git
    type: git

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.security
  - name: geerlingguy.helm
  - name: geerlingguy.ansible
  - name: grog.package
  - name: andrewrothstein.kubectl
