---
roles:
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.docker
    version: 7.4.7
  - name: xanmanning.k3s
    version: v3.4.4
  - name: r_pufky.pihole
    version: 3.0.4
  - name: l3d.unbound
    version: v1.1.0
