---
roles:
  - name: robertdebock.bootstrap
    version: 7.1.5
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.docker
    version: 7.6.0
  - name: xanmanning.k3s
    version: v3.6.1
  - name: r_pufky.pihole
    version: 3.0.4
  - name: l3d.unbound
    version: v1.1.0
