---
collections:
  - name: ksiggins.k3s
    source: https://github.com/ksiggins/k3s-ansible.git
    type: git

roles:
  - { name: geerlingguy.docker, version: 6.1.0 }
  - { name: geerlingguy.security, version: 2.2.0 }
  - { name: geerlingguy.helm, version: 1.0.1 }
  - { name: geerlingguy.ansible, version: 2.2.0 }
  - { name: grog.package, version: v1.3.1 }
  - { name: xanmanning.k3s, version: v3.3.1 }
  - { name: andrewrothstein.kubectl, version: v1.2.7 }
  - { name: r_pufky.pihole, version: 1.0.3 }
  - { name: do1jlr.unbound, version: v1.1.0 }
