---
- hosts: all
  connection: local
  gather_facts: false
  roles:
    - ssh

- hosts: all
  become: true
  roles:
    - oefenweb.apt
    - geerlingguy.security

- hosts: ansible
  become: true
  roles:
    - oefenweb.apt

- hosts: k3s_cluster
  become: true
  roles:
    - geerlingguy.docker
