---
- hosts: all
  connection: local
  gather_facts: false
  roles:
    - ssh

- hosts: all
  become: true
  roles:
    - qemu-guest-agent

- hosts: ansible
  become: true
  roles:
    - geerlingguy.ansible

- hosts: k3s_cluster
  become: true
  roles:
    - geerlingguy.docker
