- name: Remove kube directory
  file:
    path: ~/.kube
    state: absent
  when: inventory_hostname in groups['ansible']

- name: Create kube directory
  file:
    path: ~/.kube
    state: directory
  when: inventory_hostname in groups['ansible']

- name: Fetch the kubeconfig file from the k3s cluster
  become: true
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /tmp/.kube/config
    flat: true
    run_once: true
  when: inventory_hostname in groups['k3s_cluster']

- name: Copy the kubeconfig file to the ansible hosts
  copy:
    src: /tmp/.kube/config
    dest: ~/.kube/config
  when: inventory_hostname in groups['ansible']

- name: Clean tmp kube directory
  file:
    path: /tmp/.kube
    state: absent
  run_once: true
