---
- hosts: k3s_cluster
  pre_tasks:
    - import_tasks: tasks/setup-Debian.yml
      become: true
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.security
      become: true
    - role: geerlingguy.docker
      become: true
    - role: xanmanning.k3s

- hosts: k3s_server
  tasks:
    - import_tasks: tasks/kubectl/completion.yml
    - import_tasks: tasks/kubectl/k3s-copy.yml
    - import_tasks: tasks/argocd/patch.yml
      when: argocd_version is defined

- hosts: ansible
  vars:
    inventory: "{{ inventory_dir | basename }}"

  tasks:
    - import_tasks: tasks/kubectl/install.yml
      become: true
    - import_tasks: tasks/kubectl/completion.yml
    - import_tasks: tasks/kubectl/ansible-fetch.yml
    - import_tasks: tasks/argocd/install.yml
      become: true
      when: argocd_version is defined
