- hosts: k3s_cluster
  become: true
  roles:
    - grog.package
    - geerlingguy.security
    - geerlingguy.docker

- hosts: k3s_agent
  become: true
  roles:
    - grog.package

- hosts: k3s_cluster
  roles:
    - xanmanning.k3s

- hosts: ansible
  become: true
  roles:
    - andrewrothstein.kubectl

- hosts: all
  tasks:
    - import_tasks: tasks/kubeconfig-src.yml
    - import_tasks: tasks/kubeconfig-dest.yml
    - import_tasks: tasks/kubectl-completion.yml
