---
- hosts: k3s_cluster
  become: true

  pre_tasks:
    - import_tasks: tasks/setup-Debian.yml
      when: ansible_os_family == 'Debian'

  roles:
    - geerlingguy.security
    - geerlingguy.docker

- hosts: k3s_cluster
  roles:
    - xanmanning.k3s

- hosts: ansible
  become: true
  roles:
    - andrewrothstein.kubectl

- hosts: all

  vars:
    inventory: "{{ inventory_dir | basename }}"

  tasks:
    - import_tasks: tasks/kubeconfig/src.yml
    - import_tasks: tasks/kubeconfig/dest.yml
    - import_tasks: tasks/kubectl/completion.yml
    - import_tasks: tasks/kubectl/argocd-patch.yml
