roles:
  - name: geerlingguy.security
    version: 2.2.0
  - name: geerlingguy.docker
    version: 6.1.0
  - name: xanmanning.k3s
    version: v3.3.1
  - name: andrewrothstein.kubectl
    version: v1.2.7
