- name: Create manifests directory for temp configuration
  file:
    path: /tmp/k3s
    state: directory
    owner: "{{ ansible_user_id }}"
    mode: 0755
  run_once: true

- name: Copy nginx deployment manifest to first master
  template:
    src: "deployment.yml"
    dest: "/tmp/k3s/nginx-deployment.yml"
    owner: "{{ ansible_user_id }}"
    mode: 0755
  run_once: true

- name: Apply nginx deployment to pods
  command: >-
    k3s kubectl apply -f /tmp/k3s/nginx-deployment.yml
  changed_when: false
  run_once: true
