---
- name: Install and verify MetalLB deployment
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  run_once: true
  block:
    - name: Ensure MetalLB namespace exists
      ansible.builtin.command: >-
        kubectl create namespace {{ metallb_namespace }}
      register: create_ns
      failed_when: create_ns.rc != 0 and 'AlreadyExists' not in create_ns.stderr
      changed_when: "'AlreadyExists' not in create_ns.stderr"

    - name: Deploy MetalLB core manifests (CRDs + controller)
      ansible.builtin.command: >-
        kubectl apply -f
        https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
      register: metallb_apply
      changed_when: "'created' in metallb_apply.stdout or 'configured' in metallb_apply.stdout"

    - name: Wait for MetalLB controller deployment to be ready
      ansible.builtin.command: >-
        kubectl -n {{ metallb_namespace }} rollout status deployment/controller --timeout=300s
      changed_when: false

    - name: Render minimal IPAddressPool manifest
      ansible.builtin.template:
        src: ipaddresspool.yaml.j2
        dest: /tmp/ipaddresspool.yaml
        mode: '0600'

    - name: Apply IPAddressPool manifest
      ansible.builtin.command: kubectl apply -f /tmp/ipaddresspool.yaml
      register: metallb_pool_apply
      changed_when: "'created' in metallb_pool_apply.stdout or 'configured' in metallb_pool_apply.stdout"

    - name: Render L2Advertisement manifest
      ansible.builtin.template:
        src: l2advertisement.yaml.j2
        dest: /tmp/l2advertisement.yaml
        mode: '0600'

    - name: Apply L2Advertisement manifest
      ansible.builtin.command: kubectl apply -f /tmp/l2advertisement.yaml
      register: metallb_adv_apply
      changed_when: "'created' in metallb_adv_apply.stdout or 'configured' in metallb_adv_apply.stdout"

    - name: Verify MetalLB pods are running
      ansible.builtin.command: >-
        kubectl get pods -n {{ metallb_namespace }} --no-headers
      register: metallb_pods
      retries: 30
      delay: 5
      until: metallb_pods.rc == 0 and (metallb_pods.stdout | length) > 0
      changed_when: false

    - name: Wait for all MetalLB pods to become Ready
      ansible.builtin.command: >-
        kubectl wait --for=condition=ready pods --all -n {{ metallb_namespace }} --timeout=300s
      changed_when: false
