---
- name: Uninstall MetalLB and clean up resources if present
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  run_once: true
  block:
    - name: Check if MetalLB namespace exists
      ansible.builtin.command: kubectl get ns {{ metallb_namespace }}
      register: metallb_ns
      failed_when: false
      changed_when: false

    - name: Uninstall MetalLB namespaced resources if namespace exists
      ansible.builtin.command: >-
        kubectl delete all,cm,sa,role,rolebinding,svc,deploy,sts,rs,pod --all
        -n {{ metallb_namespace }} --ignore-not-found
      when: metallb_ns.rc == 0
      changed_when: false

    - name: Delete MetalLB CRDs and cluster-scoped resources
      ansible.builtin.command: >-
        kubectl delete -f
        https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
        --ignore-not-found
      changed_when: false

    - name: Delete MetalLB namespace if present
      ansible.builtin.command: kubectl delete ns {{ metallb_namespace }} --ignore-not-found
      changed_when: false
