- name: Add rancher repo
  kubernetes.core.helm_repository:
    name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
  run_once: true

- name: Deploy rancher chart inside cattle-system namespace
  kubernetes.core.helm:
    name: rancher
    chart_ref: rancher-stable/rancher
    chart_version: "{{ rancher_version }}"
    release_namespace: cattle-system
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: "{{ lookup('file', 'values-rancher.yaml') | from_yaml}}"
    values:
      hostname: "{{ rancher_hostname }}"
      bootstrapPassword: "{{ rancher_password }}"
      letsEncrypt.email: "{{ email_address }}"
  run_once: true
