- name: Read the script content from a local file
  delegate_to: localhost
  command: >-
     cat "{{ playbook_dir }}/files/install_python3.sh"
  register: script_content
  changed_when: false

- name: Create the script on the remote host
  raw: |
    echo "{{ script_content.stdout }}" > /tmp/install_python3.sh
  changed_when: false

- name: Make the script executable
  raw: chmod +x /tmp/install_python3.sh
  changed_when: false

- name: Run the script on the remote host
  raw: /tmp/install_python3.sh
  register: script_output
  changed_when: script_output.rc != 0
