---
- name: Ensure the system is up-to-date and clean cache
  yum:
    name: '*'
    state: latest
    update_cache: true
    security: true

- name: Install packages via yum (or dnf)
  yum:
    name:
      - qemu-guest-agent
      - xterm
      - vim
      - tree
      - yum-utils
      - git
      - python3
      - python3-pip
      - httpd-tools
      - iputils
      - openssh-server

- name: Check if EPEL repo is already configured
  stat:
    path: "/etc/yum.repos.d/epel.repo"
  register: epel_repofile_result

- name: Import EPEL GPG key.
  rpm_key:
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Disable Main EPEL repo
  ini_file:
    path: "/etc/yum.repos.d/epel.repo"
    section: epel
    option: enabled
    value: "false | ternary(0, 1)"
    no_extra_spaces: true
    mode: 0644

- name: Check if reboot is required
  command: needs-restarting -r
  ignore_errors: true
  register: needs_restart_result
  changed_when: needs_restart_result.rc == 1
  failed_when: needs_restart_result.rc > 1

- name: Reboot if required
  reboot:
  when: needs_restart_result.rc == 1
