---
- name: pacman
  pacman:
    name:
      - qemu-guest-agent
      - xterm
      - vi
      - tree
      - which
      - git
      - apache
      - iputils
      - fail2ban
      - neofetch
    state: present
    update_cache: yes

- name: Patch geerlingguy.security
  delegate_to: localhost
  become: false
  copy:
    src: geerlingguy.security/
    dest: "{{ playbook_dir }}/.ansible/roles/geerlingguy.security/"

- name: Ensure the English locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set the English locale as default
  command: >-
    localectl set-locale LANG=en_US.UTF-8
