---
- hosts: pihole
  become: true

  pre_tasks:
    - include_tasks: tasks/setup-{{ ansible_os_family }}.yml

  roles:
    - geerlingguy.security
    - r_pufky.pihole
    - do1jlr.unbound

  tasks:
    - import_tasks: tasks/restart-dns.yml
