- name: Scan and register ssh keys to known_hosts
  command: "ssh-keyscan {{ansible_host|default(inventory_hostname)}}"  
  register: "host_keys"
  changed_when: false  

- file: path="~/.ssh/known_hosts" state=touch  
  run_once: true  

- blockinfile:  
    dest: "~/.ssh/known_hosts"
    marker: "# {mark} This part managed by Ansible"  
    block: |  
      {% for h in groups['all'] if hostvars[h].host_keys is defined %}  
      {{ hostvars[h].host_keys.stdout }}  
      {% endfor %}  
  run_once: true
