---
all:
  children:
    os_managed:
      hosts:
        nuc4:
    podman_hosts:
      hosts:
        nuc4:
    reverse_proxy_hosts:
      hosts:
        nuc4:
    tls_hosts:
      hosts:
        nuc4:
