- name: Add metallb repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  run_once: true

- name: Deploy metallb chart inside metallb-system namespace
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: "{{ metallb_version }}"
    release_namespace: metallb-system
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: "{{ lookup('file', 'values-metallb.yaml') | from_yaml }}"
  run_once: true

- name: Apply metallb layer 2 resources
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metallb/{{ item|lower }}.yaml') | from_yaml }}"
  run_once: true
  when: metallb_mode == "layer2"
  with_items:
    - IPAddressPool
    - L2Advertisement

- name: Apply metallb layer 3 resources
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'metallb/{{ item|lower }}.yaml') | from_yaml }}"
  run_once: true
  when: metallb_mode == "layer3"
  with_items:
    - IPAddressPool
    - BGPAdvertisement
    - BGPPeer
