---
- name: Get os platform
  command: >-
    uname
  ignore_errors: true
  changed_when: false
  register: uname_result

- name: Create architecture mapping
  set_fact: 
    arch_map: "{{ arch_map | default({}) | combine ({ item.key : item.value }) }}"
  with_items:
    - { 'key': 'x86_64' , 'value': 'amd64'}
    - { 'key': 'aarch64' , 'value': 'arm64'}

- name: Download argocd to /usr/local/bin
  get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/argocd-{{ uname_result.stdout | lower }}-{{ arch_map[ansible_architecture] }}"
    dest: /usr/local/bin/argocd
    checksum: "sha256:https://github.com/argoproj/argo-cd/releases/download/{{ argocd_version }}/cli_checksums.txt"
    mode: 0755
