---
- name: Check to see if argocd-server is running
  command: >-
    kubectl get service argocd-server
    -o jsonpath="{.spec.type}"
    --kubeconfig "{{ ansible_user_dir }}/.kube/config"
  register: argocd_spec_type
  changed_when: false
  failed_when: argocd_spec_type.rc > 1
  run_once: true

- name: Change the argocd-server to a load balancer type
  command: >-
    kubectl patch service argocd-server
    -p '{"spec": { "type": "LoadBalancer" }}'
    --kubeconfig "{{ ansible_user_dir }}/.kube/config"
  run_once: true
  when: argocd_spec_type.stdout != "LoadBalancer"

- name: Update the argocd-secret dashboard password
  command: >-
    kubectl patch secret argocd-secret
    -p '{"stringData": {
      "admin.password": "{{ argocd_bcrypt_password }}",
      "admin.passwordMtime": "$(date +%FT%T%Z)"
    }}'
    --kubeconfig "{{ ansible_user_dir }}/.kube/config"
  changed_when: true
  run_once: true

- name: Delete argocd-initial-admin-secret
  command: >-
    kubectl delete secret argocd-initial-admin-secret
    --kubeconfig "{{ ansible_user_dir }}/.kube/config"
  changed_when: true
  run_once: true
