# semaphore ui
semaphore_admin: ENC[AES256_GCM,data:Qp2Lp5c=,iv:m5/lEy/b6SmZZPeNdfwxjF8fygHWDMbgT3ZFjVGCxMw=,tag:ftiwHUlrSos8CI/wC5TM1g==,type:str]
semaphore_admin_password: ENC[AES256_GCM,data:znof9CDQSHibpnfOF4xWlwsmQl8=,iv:p1F8xMPYKR+BzI2TShNCYQjNmS6C132VH0LCRnxQpCU=,tag:ciV42DigeeO8AbXoTNstUg==,type:str]
semaphore_admin_name: ENC[AES256_GCM,data:4z6g72A=,iv:GKzDRdd8Cy6V01Vxxah0da10rfbgMcOTli/eQEHuYOE=,tag:Audn7lIiOrInYTulmMT9Ww==,type:str]
semaphore_admin_email: ENC[AES256_GCM,data:E1l/zd3F4Ts6OYBoPfmM,iv:ZiC+v5zDMV4YGzdtKfr9XxytzYmuzNUxMGf0O3Yb0cs=,tag:B4+/dU6cdc6dqc8+Y5YCkw==,type:str]
# database
semaphore_db_user: ENC[AES256_GCM,data:zY4yB2XHHjGE,iv:2VqWYEFN7RLYIDrC3P+cwF+BDym0L5sTq2Da9tFlH6E=,tag:Ho10mkTiOW0I0prYv+TkpA==,type:str]
semaphore_db_password: ENC[AES256_GCM,data:RK0J5kpnP4SoO8j0w04nCqevrKI=,iv:GjM87xbRv0oEM1Um9qQnd0T1HdUh43oD2qBLNxjUI4c=,tag:AL+lt1CqOtd70eTvt1ki+Q==,type:str]
semaphore_access_key_encryption: ENC[AES256_GCM,data:0vnGAt7A4kkWnkJ/c/hB3u/isP7bU3ZbMz1ljsWjBgWyH7JZiTg6PLsmsys=,iv:Oj5NP9zrs1Hmx2C7ek7TVRXu2G4SunTxSt6LirR2ev0=,tag:9uyoKJXRK+JhAlPB5H6MIg==,type:str]
# database backups
smb_user: ENC[AES256_GCM,data:JAt/63zNSkPP,iv:3OEew5cNjgbzt44MywFqkXXAnT4gVVmhcKoTmPkD2RM=,tag:4pPC7d8v2CAAHt1K972ZzA==,type:str]
smb_password: ENC[AES256_GCM,data:rfEmN42DSXUWlSXb9KGO3Hia6TY=,iv:jwlVGHipe0EvIT3xtn5hq2Eqk36WILSGHI8KApyNOJ8=,tag:7/rLiQx9VdCTEggWzaSxaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRi9jS2FSaGNtZmNlMi92
            YzE2VE4rdWpwb2E2Z1JoWkhrampSdXlrWFZJCjcvVWNTOW5SUjc0Ym5qdEFTRS94
            RDJqTHdGcFVQRXhpaFJSa1AyNTVVZ2sKLS0tIGFoUStKNkJ2dlRUeVRrZWVuU3ZT
            dGxnZ21xOERGRVRYY0tLMENIRE1RY2sKPpfLyjZVESK78AeUHTbnn3Cn1mpX25RA
            5V8LlgYITCkeYnZSOTnl+F2ehjALw9Zc4pTocjPAh4Ynk5cbOsNbJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehm0ehd2v2emfuycf2p0suhg94ej29zcu96ffmh3t6afchhjd99sxc4984
    encrypted_regex: ^(.*)$
    lastmodified: "2026-09-07T14:39:30Z"
    mac: ENC[AES256_GCM,data:2pNDoc7yRLeMsrIzIc5xUVPCAeg1GWyISsbUGyJhs7vWOhT9/ZhxnM0zJJykuVJivuOUtk7JUCjeQuzJdA5MiGBoEgNe1S+fKkZmHnADYw5jTgPu9pbcQNZeS5SgZ4XEKK/BsNc1Ynh9fcd36gTYawcIbjEK3CD7SXUoH+Kbr9Y=,iv:Qv7jk5gyLP0WJFvuJl+8Et6slUjdBztGbWdo760gBL0=,tag:pYK0PzkOiTuo/ir8l8V86g==,type:str]
    version: 3.13.2
