---
- name: Install packages via apt
  apt:
    name:
      - qemu-guest-agent
      - xterm
      - vim
      - tree
      - debianutils
      - git
      - python3
      - python3-pip
      - python3-netaddr
      - apache2-utils
      - iputils-ping
    state: present
    update_cache: yes
    cache_valid_time: 3600
