- name: Copy requirements.txt to remote
  copy:
    src: "{{ playbook_dir }}/files/requirements.txt"
    dest: /tmp/requirements.txt

- name: Install python packages via pip
  pip:
    requirements: /tmp/requirements.txt

- name: Clean tmp requirements.txt
  file:
    path: /tmp/requirements.txt
    state: absent
