- name: Copy requirements.txt to remote
  copy:
    src: "{{ playbook_dir }}/files/requirements.txt"
    dest: /tmp/requirements.txt

- name: Install python packages via pip
  pip:
    break_system_packages: true
    requirements: /tmp/requirements.txt
