---
- name: Update apt cache and run dist upgrade
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist

- name: Install packages via apt
  apt:
    name:
      - qemu-guest-agent
      - xterm
      - vim
      - tree
      - debianutils
      - git
      - python3
      - python3-pip
      - python3-netaddr
      - apache2-utils
      - iputils-ping

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required (if required)
  reboot:
  when:
    reboot_required_file.stat.exists == true and
    ansible_default_ipv4.address != hostvars.localhost.ansible_default_ipv4.address

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
