---
- name: Copy requirements.txt to remote
  ansible.builtin.copy:
    src: files/requirements.txt
    dest: /tmp/requirements.txt
    mode: '0644'

- name: Install python packages via pip
  ansible.builtin.pip:
    break_system_packages: true
    requirements: /tmp/requirements.txt
