---
- name: Update package cache and upgrade all packages
  apt:
    update_cache: yes
    upgrade: dist
    force_apt_get: yes
  register: apt_upgrade
  changed_when: apt_upgrade.changed

- name: Autoremove unused packages
  apt:
    autoremove: yes
    force_apt_get: yes

- name: Autoclean cached packages
  apt:
    autoclean: yes
    force_apt_get: yes

- name: Install packages via apt
  apt:
    name:
      - qemu-guest-agent
      - xterm
      - vim
      - tree
      - debianutils
      - git
      - python3
      - python3-pip
      - python3-netaddr
      - apache2-utils
      - iputils-ping
      - openssh-server
      - neofetch
    state: present
    update_cache: false
    force_apt_get: yes

- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: "Reboot triggered due to package update"
    connect_timeout: 5
    reboot_timeout: 600
    test_command: whoami
  when: reboot_required_file.stat.exists
