apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
  aggregationLength: 32
  localPref: 100
  communities:
    - 65535:65282
