---
- hosts: localhost
  connection: local
  gather_facts: true

- hosts: ansible
  become: true

  pre_tasks:
    - include_tasks: tasks/setup-{{ ansible_os_family }}.yml
    - import_tasks: tasks/setup-pip.yml

  roles:
    - geerlingguy.security
