- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: latest
    update_cache: true
  run_once: true

- name: Install kubernetes.core.k8s pip dependencies
  ansible.builtin.pip:
    name:
      - kubernetes
      - PyYAML
      - jsonpatch
  run_once: true
