---
- name: Create kube directory
  file:
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
    mode: 0700

- name: Copy the kubeconfig file to user home
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_user_dir }}/.kube/config"
    owner: "{{ ansible_user_id }}"
    remote_src: true
    mode: 0600

- name: Configure kubectl cluster for server endpoint
  command: >-
    kubectl config set-cluster default
      --server https://{{ k3s_registration_address | default(ansible_host) }}:6443
      --kubeconfig {{ ansible_user_dir }}/.kube/config
  changed_when: true

- name: Set kubeconfig env in bashrc
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: ^export KUBECONFIG=${HOME}/.kube/config
    line: export KUBECONFIG=${HOME}/.kube/config
