- hosts: helm
  become: true
  roles:
    - grog.package
    - geerlingguy.helm

- hosts: helm
  tasks:
    - import_tasks: tasks/cert-manager/install.yml
    - import_tasks: tasks/kube-prometheus-stack/install.yml
