- hosts: helm
  become: true
  roles:
    - grog.package
    - geerlingguy.helm

- hosts: helm
  tasks:
    - import_tasks: tasks/metallb/install.yml
    - import_tasks: tasks/traefik/install.yml
    - import_tasks: tasks/cert_manager/install.yml
