- hosts: helm
  become: true
  roles:
    - grog.package
    - geerlingguy.helm

- hosts: helm
  tasks:
    - import_tasks: tasks/metallb.yml
    - import_tasks: tasks/traefik.yml
    - import_tasks: tasks/cert-manager.yml
