argocd_admin_user: ENC[AES256_GCM,data:FT1pWbM=,iv:WEnurv0BELZLAtrHZAB/oTVsycIfp2C5L1Wl9YIsjWQ=,tag:kxrXNOFtQhXq5cqoLwUSUQ==,type:str]
argocd_admin_password: ENC[AES256_GCM,data:L4DLdn3lStSEOP0YwQQaF0XGGpfZmGvW,iv:onI8fR1J28di0ScThSvqb96espJBTIAPqGfNCu8m30A=,tag:oAnfKHEH0YXlmjt92NhdxQ==,type:str]
argocd_admin_bcrypt_password: ENC[AES256_GCM,data:I+tofeKlassqY5+LaTZMJ+h9OM8dwuIXOXVavygGzpc8eehEfX1rohR2KY/QkYhHFkh10Cde7686ELGI,iv:GJAHWpwkxSqKfKguOvI59W+yGb7+FUTPvFg2254fWmw=,tag:KniYl++ORLgOuXAtmoEkZA==,type:str]
argocd_readonly_user: ENC[AES256_GCM,data:+SOzMfPKt1U=,iv:qRSLGWt9GkH6wBfP6Rm7xlqreNSf/3frvD35YeHcYB0=,tag:6Iu9JzBSjzhJFOUuP5eJiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM1lmNHZxTG5iNzJJL2pR
            MU1kUStMV2NXY25LckpEc2FHVGs2YndodFNzCkJyUzJpQ0FQV0NnOVlKbkhhUVVv
            NkxmcThNWm91MTlxY1VVejQ0bU5lcU0KLS0tIFppejBIU2ZzMGx3SUVtV2lBTHgz
            NER6RXc2WElvYXYvNGdXSHYxdndFb0kKRGP1Y30Dif2AZv2Io1y1UdPnP8Lk7Ss9
            Jl5nVXbiQkJxc0d/cCheucb/AGiDounkDVEfy9Gd9sfSqR61BNj32g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ehm0ehd2v2emfuycf2p0suhg94ej29zcu96ffmh3t6afchhjd99sxc4984
    encrypted_regex: ^(.*)$
    lastmodified: "2026-09-07T14:39:32Z"
    mac: ENC[AES256_GCM,data:GbxNNVD2cyX2u6A4ihYXlOgz/Et1MoXoFr9mU01uKCLr8zUeJ4ePZRkgEu8KoFjPc2zFSHJT2glNyMMvaouGt5wyL54E5qARHUDQnFSRXqIeHD2/XyURhltgEb70LQEStz428tPJuiVBSJzJi9HJIDqUOIw9smdRedpd7pctiYQ=,iv:/ggKJp6jk67tMhaTZStvfM1v/y+R9XGof+hhMmjc/NA=,tag:72gr5hTAxqSm/6ery8VZkw==,type:str]
    version: 3.13.2
