- name: Add traefik repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts
  run_once: true

- name: Deploy traefik chart inside traefik-v2 namespace
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_version }}"
    release_namespace: traefik-v2
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: "{{ lookup('file', 'values-traefik.yaml') | from_yaml}}"
  run_once: true

- name: Apply traefik dashboard ingressroute
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'traefik/dashboard.yaml.j2') | from_yaml }}"
  run_once: true
