- name: Remove traefik chart
  kubernetes.core.helm:
    name: traefik
    release_namespace: traefik-v2
    state: absent
    wait: true
  run_once: true

- name: Remove traefik repo
  kubernetes.core.helm_repository:
    name: traefik
    state: absent
  run_once: true

- name: Remove traefik-v2 namespace
  kubernetes.core.k8s:
    name: traefik-v2
    kind: Namespace
    state: absent
  run_once: true

- name: Download traefik CRDs
  ansible.builtin.get_url:
    url: https://github.com/traefik/traefik-helm-chart/releases/download/{{ traefik_version }}/traefik.yaml
    dest: /tmp/traefik.crds.yaml
  run_once: true

- name: Remove traefik CRDs
  kubernetes.core.k8s:
    state: absent
    src: /tmp/traefik.crds.yaml
  run_once: true

- name: Remove downloaded tmp CRD file
  ansible.builtin.file:
    path: /tmp/traefik.crds.yaml
    state: absent
