---
- name: Gather environment and context from Ansible controller
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Show controller environment variables
      ansible.builtin.command: env
      register: env_output
      changed_when: false  # Prevents false "changed" status

    - name: Print environment variables
      ansible.builtin.debug:
        msg: "{{ env_output.stdout_lines }}"

    - name: Show Ansible context vars (if any)
      ansible.builtin.debug:
        var: ansible_env

    - name: Show hostvars for localhost
      ansible.builtin.debug:
        var: hostvars['localhost']
