---
- name: Gather all possible facts from remote host
  hosts: servers
  gather_facts: false

  tasks:
    - name: Force full fact gathering
      ansible.builtin.setup:
        gather_subset:
          - all
          - network
          - hardware
          - virtual
          - ohai
          - facter
          - selinux

    - name: Print all gathered facts
      ansible.builtin.debug:
        var: ansible_facts
