---
- name: Install or update Pi-hole
  hosts: pihole
  become: true

  roles:
    - role: r_pufky.pihole
      tags: [install]
    - role: l3d.unbound
      tags: [install]
    - role: update_pihole
      tags: [update]
