---
- name: Check if /boot/firmware/cmdline.txt
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline_check
  changed_when: false
  when:
    - ansible_os_family == 'Debian'
    - ansible_facts['architecture'] in ['armv7l', 'aarch64']

- name: Manage cgroup kernel parameters
  when: cmdline_check is defined and cmdline_check.get('stat', {}).get('exists', false)
  block:

    - name: Install cgroup kernel parameters
      ansible.builtin.include_tasks: install.yml
      when: cgroup_state == 'present'

    - name: Uninstall cgroup kernel parameters
      ansible.builtin.include_tasks: uninstall.yml
      when: cgroup_state == 'absent'
