---
- name: Read existing /boot/firmware/cmdline.txt
  ansible.builtin.slurp:
    path: /boot/firmware/cmdline.txt
  register: cmdline_raw

- name: Decode cmdline content
  ansible.builtin.set_fact:
    cmdline_current: "{{ cmdline_raw.content | b64decode | trim }}"

- name: Compute cleaned cmdline without cgroup parameters
  ansible.builtin.set_fact:
    cmdline_cleaned: >-
      {{ cmdline_current
        | regex_replace('cgroup_enable=cpuset', '')
        | regex_replace('cgroup_enable=memory', '')
        | regex_replace('cgroup_memory=1', '')
        | regex_replace('\s+', ' ')
        | trim
      }}

- name: Get existing file mode for preservation
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: cmdline_stat

- name: Remove cgroup kernel parameters if present
  ansible.builtin.copy:
    content: "{{ cmdline_cleaned }}\n"
    dest: /boot/firmware/cmdline.txt
    owner: root
    group: root
    mode: "{{ '%04o' % cmdline_stat.stat.mode | int(base=8) }}"
  when: cmdline_current != cmdline_cleaned
  notify: Reboot system
